### PR TITLE
Release 3.3.5

### PR DESCRIPTION
**Pull request by kikettas**
### Description
Release 3.3.5

### How to test
Nothing to test

### Merging
Merge once `release-3.3.5` is merge into `develop`

### CODE REVIEW

**Comment by nsobadjiev** [comment]
This is the small release before the multipage one? With the configurable Drag & Drop tutorial?
Why didn't you make a release branch?

**Comment by kikettas** [comment]
@nsobadjiev is the other PR 😅

**Comment by nsobadjiev** [comment]
That's not correct, though. You make a release branch, you bump the version and you merge the release branch **into** master and also the release branch into develop.

What you have done is to merge the release branch into develop and develop into master.

**Comment by kikettas** [comment]
But at the end it's the same, isn't it?

**Comment by nsobadjiev** [comment]
Well, if you look at the branches chart, it will be a little different. Don't you have a GitFlow thingy in SourceTree or whatever you're using?

**Pull request merged**
